/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package seguridad;


import clientes.ClienteService;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.security.Provider;
import java.util.List;
import javax.swing.JTable;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;
import clientes.Cliente;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.JScrollPane;
import Model.AppContext;
import menu.Plato;

/**
 *
 * @author USER
 */
public class JP_Inicio extends javax.swing.JPanel {

    /**
     * Creates new form Inicio
     */
    DefaultTableModel modelo;
    public JP_Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        bga = new javax.swing.JPanel();
        jpT = new javax.swing.JPanel();
        lblT = new javax.swing.JLabel();
        btnVerDetalleCliente = new javax.swing.JButton();
        jpP = new javax.swing.JPanel();
        lblP = new javax.swing.JLabel();
        btnverdetallemenu = new javax.swing.JButton();
        jpS = new javax.swing.JPanel();
        lblS = new javax.swing.JLabel();
        btn3 = new javax.swing.JButton();
        jpI = new javax.swing.JPanel();
        lblE = new javax.swing.JLabel();
        txtI = new javax.swing.JTextField();
        txtE = new javax.swing.JTextField();
        btn4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        jScrollPane1.setViewportView(jEditorPane1);

        setPreferredSize(new java.awt.Dimension(680, 0));

        jpT.setBackground(new java.awt.Color(51, 0, 255));

        lblT.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblT.setForeground(new java.awt.Color(255, 255, 255));
        lblT.setText("Total de clientes registrados");

        btnVerDetalleCliente.setBackground(new java.awt.Color(0, 0, 0));
        btnVerDetalleCliente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnVerDetalleCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnVerDetalleCliente.setText("ver detalle");
        btnVerDetalleCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerDetalleClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpTLayout = new javax.swing.GroupLayout(jpT);
        jpT.setLayout(jpTLayout);
        jpTLayout.setHorizontalGroup(
            jpTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTLayout.createSequentialGroup()
                .addGroup(jpTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpTLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(btnVerDetalleCliente))
                    .addGroup(jpTLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lblT, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jpTLayout.setVerticalGroup(
            jpTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblT)
                .addGap(18, 18, 18)
                .addComponent(btnVerDetalleCliente)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jpP.setBackground(new java.awt.Color(0, 153, 51));

        lblP.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblP.setForeground(new java.awt.Color(255, 255, 255));
        lblP.setText("Menu del Dia");

        btnverdetallemenu.setBackground(new java.awt.Color(0, 0, 0));
        btnverdetallemenu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnverdetallemenu.setForeground(new java.awt.Color(255, 255, 255));
        btnverdetallemenu.setText("ver detalle");
        btnverdetallemenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnverdetallemenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpPLayout = new javax.swing.GroupLayout(jpP);
        jpP.setLayout(jpPLayout);
        jpPLayout.setHorizontalGroup(
            jpPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jpPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnverdetallemenu)
                    .addComponent(lblP, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpPLayout.setVerticalGroup(
            jpPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblP)
                .addGap(18, 18, 18)
                .addComponent(btnverdetallemenu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpS.setBackground(new java.awt.Color(0, 0, 153));

        lblS.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblS.setForeground(new java.awt.Color(255, 255, 255));
        lblS.setText("Productos mas vendidos");

        btn3.setBackground(new java.awt.Color(0, 0, 0));
        btn3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn3.setForeground(new java.awt.Color(255, 255, 255));
        btn3.setText("ver detalle");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpSLayout = new javax.swing.GroupLayout(jpS);
        jpS.setLayout(jpSLayout);
        jpSLayout.setHorizontalGroup(
            jpSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(btn3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpSLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblS, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        jpSLayout.setVerticalGroup(
            jpSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn3)
                .addGap(34, 34, 34))
        );

        jpI.setBackground(new java.awt.Color(0, 153, 204));

        lblE.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblE.setForeground(new java.awt.Color(255, 255, 255));
        lblE.setText("Ingresos y egresos del mes");

        btn4.setBackground(new java.awt.Color(0, 0, 0));
        btn4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn4.setForeground(new java.awt.Color(255, 255, 255));
        btn4.setText("ver detalle");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpILayout = new javax.swing.GroupLayout(jpI);
        jpI.setLayout(jpILayout);
        jpILayout.setHorizontalGroup(
            jpILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpILayout.createSequentialGroup()
                .addGroup(jpILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpILayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jpILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblE, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpILayout.createSequentialGroup()
                                .addComponent(txtI, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtE, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jpILayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(btn4)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jpILayout.setVerticalGroup(
            jpILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpILayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 585, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 239, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout bgaLayout = new javax.swing.GroupLayout(bga);
        bga.setLayout(bgaLayout);
        bgaLayout.setHorizontalGroup(
            bgaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgaLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(bgaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(bgaLayout.createSequentialGroup()
                        .addGroup(bgaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jpS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jpT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                        .addGroup(bgaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jpP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jpI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(45, 45, 45))
        );
        bgaLayout.setVerticalGroup(
            bgaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgaLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(bgaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(bgaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
         double n1 = Double.parseDouble(txtI.getText());
         double n2 = Double.parseDouble(txtE.getText());
         
         DefaultPieDataset datos = new DefaultPieDataset();
         datos.setValue("INGRESOS", n1);
         datos.setValue("EGRESOS", n2);
         
         JFreeChart grafico_circular = ChartFactory.createPieChart(
         "INGRESOS / EGRESOS",  // título del gráfico
          datos,                 // datos
          true,                  // incluir leyenda
          true,                  // incluir tooltips
          false                  // no generar URL
        );
         
         ChartPanel panel = new ChartPanel(grafico_circular);
         panel.setMouseWheelEnabled(true);
         panel.setPreferredSize(new Dimension(585,235));
         
         jPanel1.removeAll();
         jPanel1.setLayout(new BorderLayout());
         jPanel1.add(panel, BorderLayout.CENTER);
         jPanel1.setLayout(new BorderLayout());
         jPanel1.add(panel,BorderLayout.NORTH);
         jPanel1.validate();
         jPanel1.repaint();
         
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        org.jfree.data.category.DefaultCategoryDataset datos = new org.jfree.data.category.DefaultCategoryDataset();
        datos.setValue(150, "Materiales", "Planchas");
        datos.setValue(300, "Materiales", "Tornillos");
        datos.setValue(200, "Materiales", "Masilla");
        datos.setValue(180, "Materiales", "Cinta");
        datos.setValue(100, "Materiales", "Perfiles Metálicos");

    
        org.jfree.chart.JFreeChart grafico_barras = org.jfree.chart.ChartFactory.createBarChart3D(
        "MATERIALES MAS VENDIDOS",     
        "Material",                             
        "Cantidad (unidades)",                  
        datos,                                  
        org.jfree.chart.plot.PlotOrientation.VERTICAL,
        true,                                   
        true,                                   
        false                                  
    );

    
        org.jfree.chart.ChartPanel panel = new org.jfree.chart.ChartPanel(grafico_barras);
        panel.setMouseWheelEnabled(true);
        panel.setPreferredSize(new java.awt.Dimension(585,235));
 
        jPanel1.removeAll(); // limpia el panel
        jPanel1.setLayout(new java.awt.BorderLayout());
        jPanel1.add(panel, java.awt.BorderLayout.CENTER);
        jPanel1.validate();
        jPanel1.repaint();
    }//GEN-LAST:event_btn3ActionPerformed
    /*private void cargarDatos(String filtro){
        modelo.setRowCount(0);
        List<com.smart.home.model.Cliente> lista = dao.listarClientes(filtro);
        for (com.smart.home.model.Cliente c : lista) {
            modelo.addRow(new Object[]{
                c.getNombre(), c.getApellido(), c.getDniRuc(), c.getTelefono(), c.getCorreo(), c.getTipo()
            });
    }*/
    private void btnVerDetalleClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerDetalleClienteActionPerformed
         String[] columnas = {"ID", "Nombre","Apellido","DNI","Correo","Telefono"};
        modelo=new DefaultTableModel(columnas,0);
        JTable tabla=new JTable(modelo);
        tabla.setFillsViewportHeight(true);
        tabla.setRowHeight(25);
        
       JScrollPane scroll=new JScrollPane(tabla);
       jPanel1.add(scroll, java.awt.BorderLayout.CENTER);
       
      
          List<Cliente> ListaCliente=AppContext.clienteservice.listarcliente();
          
        
        
        for(Cliente c:ListaCliente){
           Object[] fila={c.getId(),c.getNombre(),c.getApellido(),c.getDni(),c.getCorreo(),c.getTelefono()};
          
           modelo.addRow(fila);
        }
        jPanel1.removeAll();
        jPanel1.setLayout(new java.awt.BorderLayout());
        
     javax.swing.JLabel titulo = new javax.swing.JLabel("Clientes", javax.swing.SwingConstants.CENTER);
        titulo.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));

        jPanel1.add(titulo, java.awt.BorderLayout.NORTH);
        jPanel1.add(scroll, java.awt.BorderLayout.CENTER);

    
        jPanel1.validate();
        jPanel1.repaint();
        
        
         
      
 /*String[][] clientes = {
        {"Construcciones López", "Lima"},
        {"Drywall Express", "Callao"},
        {"Estructuras del Norte", "Trujillo"},
        {"Proyectos Sánchez", "Arequipa"},
        {"Servicios JM", "Chiclayo"},
        {"Acabados Rivera", "Piura"},
        {"Soluciones Integrales Torres", "Huancayo"},
        {"Innovaciones Drywall Perú", "Cusco"},
        {"Decoraciones Martínez", "Tacna"},
        {"Montajes Técnicos S.A.C.", "Ica"},
        {"Grupo DryWall del Sur", "Arequipa"},
        {"Construcciones Vega", "Lambayeque"},
        {"Arquitectura Moderna SAC", "Lima"},
        {"Sistemas Dryline", "Trujillo"},
        {"Instalaciones Herrera", "Puno"},
        {"Paneles y Acabados Perú", "Tumbes"},
        {"Servicios Técnicos Bravo", "Huaraz"},
        {"Construcciones y Reformas Gamarra", "Ayacucho"},
        {"Proyectos Metálicos Flores", "Cajamarca"},
        {"Acabados & Diseño SAC", "Moquegua"}
    };
   JTable table= new JTable(clientes,columnas);
 /*
   

        String[] columnas = {"Cliente", "Ciudad"};

        
       JTable tabla = new JTable(clientes, columnas);
       javax.swing.JScrollPane scroll = new javax.swing.JScrollPane(tabla);
       scroll.setPreferredSize(new java.awt.Dimension(250, 120));

    
       jPanel1.removeAll();
       jPanel1.setLayout(new java.awt.BorderLayout());

    
       javax.swing.JLabel titulo = new javax.swing.JLabel("👤 Clientes Registrados", javax.swing.SwingConstants.CENTER);
       titulo.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));

       jPanel1.add(titulo, java.awt.BorderLayout.NORTH);
       jPanel1.add(scroll, java.awt.BorderLayout.CENTER);

    
       jPanel1.validate();
       jPanel1.repaint();*/


        
       
    }//GEN-LAST:event_btnVerDetalleClienteActionPerformed

    private void btnverdetallemenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnverdetallemenuActionPerformed
         String[] columnas = {"ID", "Nombre","precio","Disponible","Categoria"};
        modelo=new DefaultTableModel(columnas,0);
        JTable tabla=new JTable(modelo);
        tabla.setFillsViewportHeight(true);
        tabla.setRowHeight(25);
        
       JScrollPane scroll=new JScrollPane(tabla);
       jPanel1.add(scroll, java.awt.BorderLayout.CENTER);
       
    
    
       
      
          List<Plato> ListaPlatos=AppContext.menuservice.listaplatos();
          
        
        
        for(Plato p:ListaPlatos){
           Object[] fila={p.getId(),p.getNombre(),p.getPrecio(),p.isDisponible(),p.getCategoria()};
          
           modelo.addRow(fila);
        }
        jPanel1.removeAll();
        jPanel1.setLayout(new java.awt.BorderLayout());
        
     javax.swing.JLabel titulo = new javax.swing.JLabel("MENU DEL DIA", javax.swing.SwingConstants.CENTER);
        titulo.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));

        jPanel1.add(titulo, java.awt.BorderLayout.NORTH);
        jPanel1.add(scroll, java.awt.BorderLayout.CENTER);

    
        jPanel1.validate();
        jPanel1.repaint();
        
    }//GEN-LAST:event_btnverdetallemenuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bga;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btnVerDetalleCliente;
    private javax.swing.JButton btnverdetallemenu;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpI;
    private javax.swing.JPanel jpP;
    private javax.swing.JPanel jpS;
    private javax.swing.JPanel jpT;
    private javax.swing.JLabel lblE;
    private javax.swing.JLabel lblP;
    private javax.swing.JLabel lblS;
    private javax.swing.JLabel lblT;
    private javax.swing.JTextField txtE;
    private javax.swing.JTextField txtI;
    // End of variables declaration//GEN-END:variables
}
